name: Build test

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: cat install.sh
      
    - name: Build
      run: |
        LNMP_Auto="y" DBSelect="5" DB_Root_Password="lnmp.org" InstallInnodb="y" PHPSelect="9" SelectMalloc="2" ./install.sh lnmp
